#if !defined(AFX_SKSTU_ERROR_H__5147C_79417AF0_5FFEDD3EDE4B655_7F16__HEAD__)
#define AFX_SKSTU_ERROR_H__5147C_79417AF0_5FFEDD3EDE4B655_7F16__HEAD__

#define SK_ERRNO_MAP(XX)\
XX(0, SYSTEM_OK, "SYSTEM_OK")\
XX(1, SYSTEM_ERROR_UNKNOWN,"SYSTEM_ERROR_UNKNOWN")\
XX(2, SYSTEM_ERROR_POINTER_NULL,"SYSTEM_ERROR_POINTER_NULL")\
XX(3, SYSTEM_ERROR_BUFFER_OVERFLOW,"SYSTEM_ERROR_BUFFER_OVERFLOW")\
XX(4, SYSTEM_ERROR_PROCESS,"SYSTEM_ERROR_PROCESS")\
XX(5, SYSTEM_NO,"SYSTEM_NO")\
XX(6, SYSTEM_FAILED,"SYSTEM_FAILED")\
XX(7, SYSTEM_SUCCESS,"SYSTEM_SUCCESS")\
XX(8, SYSTEM_ERROR,"SYSTEM_ERROR")\
XX(1000, TRADE_FOLLOWOBJ_SUCCESS,   "TRADE_FOLLOWOBJECT_SUCCESS")\
XX(1001, TRADE_FOLLOWOBJ_FAILED,   "TRADE_FOLLOWOBJECT_FAILED")\
XX(1002, TRADE_FOLLOWOBJ_FUNCTION_DISABLE,   "TRADE_FOLLOWOBJ_FUNCTION_DISABLE")\
XX(1003, TRADE_FOLLOWOBJ_PROCESS_BREAK,   "TRADE_FOLLOWOBJ_PROCESS_BREAK")\
XX(1004, TRADE_FOLLOWOBJ_VALUE_LIMIT, "TRADE_FOLLOWOBJ_VALUE_LIMIT")\
XX(1005, TRADE_FOLLOWOBJ_ERROR_INVALID_RESULT, "TRADE_FOLLOWOBJ_ERROR_INVALID_RESULT")\
XX(1006, TRADE_FOLLOWOBJ_ERROR_UNKNOWN_DATATYPE, "TRADE_FOLLOWOBJ_ERROR_UNKNOWN_DATATYPE")\
XX(1007, TRADE_FOLLOWOBJ_ERROR_TRADEREQUEST, "TRADE_FOLLOWOBJ_ERROR_TRADEREQUEST")\
XX(1008, TRADE_FOLLOWOBJ_ERROR_VALUE_NULL, "TRADE_FOLLOWOBJ_ERROR_VALUE_NULL")\
XX(1009, TRADE_FOLLOWOBJ_ERROR_DATA_MISSING,"TRADE_FOLLOWOBJ_ERROR_DATA_MISSING")\
XX(1010, TRADE_FOLLOWOBJ_ERROR_LOGIN_NULL,"TRADE_FOLLOWOBJ_ERROR_LOGIN_NULL")\
XX(1011, TRADE_FOLLOWOBJ_ERROR_DATA_TYPE_NOTSUPPORTED,"TRADE_FOLLOWOBJ_ERROR_DATA_TYPE_NOTSUPPORTED")\
XX(1012, TRADE_FOLLOWOBJ_WARN_FOLLOW_PATH_BROKEN,"TRADE_FOLLOWOBJ_WARN_FOLLOW_PATH_BROKEN")\
XX(1013, TRADE_FOLLOWOBJ_ERROR_INVALID_VOLUME,"TRADE_FOLLOWOBJ_WARN_INVALID_VOLUME")\
XX(1014, TRADE_FOLLOWOBJ_WARN_FOLLOW_DISABLE, "TRADE_FOLLOWOBJ_WARN_FOLLOW_DISABLE")\
XX(1015, TRADE_FOLLOWOBJ_WARN_POSITION_COUNT_OVERRUN, "TRADE_FOLLOWOBJ_WARN_POSITION_COUNT_OVERRUN")\
XX(1016, TRADE_FOLLOWOBJ_WARN_TYPETYPE_BROKEN, "TRADE_FOLLOWOBJ_WARN_TYPETYPE_BROKEN")\
XX(1017, TRADE_FOLLOWOBJ_WARN_TIMEFRAME_BROKEN, "TRADE_FOLLOWOBJ_WARN_TYPETYPE_BROKEN")\
XX(1018, TRADE_FOLLOWOBJ_ERROR_SYMBOL_NULL, "TRADE_FOLLOWOBJ_ERROR_SYMBOL_NULL")\
XX(1019, TRADE_FOLLOWOBJ_WARN_SYMBOL_NOTFOLLOW, "TRADE_FOLLOWOBJ_WARN_SYMBOL_NOTFOLLOW")\
XX(1020, TRADE_FOLLOWOBJ_WARN_SYMBOL_ONLYFOLLOW, "TRADE_FOLLOWOBJ_WARN_SYMBOL_ONLYFOLLOW")\
XX(1021, TRADE_FOLLOWOBJ_WARN_EDITPOSSLTP_DISABLE, "TRADE_FOLLOWOBJ_WARN_EDITPOSSLTP_DISABLE")\
XX(1022, TRADE_FOLLOWOBJ_ERROR_NOTSUPPORTED_POSITION_ACTION, "TRADE_FOLLOWOBJ_ERROR_NOTSUPPORTED_POSITION_ACTION")\
XX(1023, TRADE_FOLLOWOBJ_WARN_OVERRUN_VOLUME, "TRADE_FOLLOWOBJ_WARN_OVERRUN_VOLUME")\
XX(1024, TRADE_FOLLOWOBJ_ERROR_VOLUME_NULL, "TRADE_FOLLOWOBJ_ERROR_VOLUME_NULL")\
XX(1025, TRADE_FOLLOWOBJ_ERROR_POSITION_NULL, "TRADE_FOLLOWOBJ_ERROR_POSITION_NULL")\
XX(1026, TRADE_FOLLOWOBJ_WARN_SIGNAL_POSITION_NULL, "TRADE_FOLLOWOBJ_WARN_SIGNAL_POSITION_NULL")\
XX(1027, TRADE_FOLLOWOBJ_ERROR_FOLLOW_CONFIGURE, "TRADE_FOLLOWOBJ_ERROR_FOLLOW_CONFIGURE")\
XX(1028, TRADE_FOLLOWOBJ_ERROR_PROCESS_MISSPARAM, "TRADE_FOLLOWOBJ_ERROR_PROCESS_MISSPARAM")\
XX(1029, TRADE_FOLLOWOBJ_ERROR_SIGNAL_INVALID, "TRADE_FOLLOWOBJ_ERROR_SIGNAL_INVALID")\
XX(1030, TRADE_FOLLOWOBJ_WARN_SIGNAL_NOTFOLLOWUSER, "TRADE_FOLLOWOBJ_WARN_SIGNAL_NOTFOLLOWUSER")\
XX(1031, TRADE_FOLLOWOBJ_WARN_TASK_PROCESSING, "TRADE_FOLLOWOBJ_WARN_TASK_PROCESSING")\
XX(0x10000,SYSTEM_RET_SUCCESS,"SYSTEM_RET_SUCCESS")\
XX(0x11000,SYSTEM_RET_ERROR,"SYSTEM_RET_ERROR")\
XX(0x11001,SYSTEM_RET_ERROR_NULL_POINTER,"SYSTEM_RET_ERROR_NULL_POINTER")\
XX(0x11002,SYSTEM_RET_ERROR_PARAMETERS,"SYSTEM_RET_ERROR_PARAMETERS")\
XX(0x11003,SYSTEM_RET_ERROR_REQUEST,"SYSTEM_RET_ERROR_REQUEST")\
XX(0x20000,LICENSE_RET_SUCCESS,"LICENSE_RET_SUCCESS")\
XX(0x21000,LICENSE_RET_ERROR,"LICENSE_RET_ERROR")\
XX(0x21010, LICENSE_RET_ERROR_BUFFER_EMPTY,"LICENSE_RET_ERROR_BUFFER_EMPTY")\
XX(0x21020, LICENSE_RET_ERROR_DECODE_FAILED,"LICENSE_RET_ERROR_DECODE_FAILED")\
XX(0x21030, LICENSE_RET_ERROR_DATA_VERIFY_FAILED,"LICENSE_RET_ERROR_DATA_VERIFY_FAILED")\
XX(0x21040, LICENSE_RET_ERROR_PRODUCT_TYPE,"LICENSE_RET_ERROR_PRODUCT_TYPE")\
XX(0x21050, LICENSE_RET_ERROR_HARDWAREINFO,"LICENSE_RET_ERROR_HARDWAREINFO")\
XX(0x21060, LICENSE_RET_ERROR_HARDWAREINFO_BIOS,"LICENSE_RET_ERROR_HARDWAREINFO_BIOS")\
XX(0x21070, LICENSE_RET_ERROR_HARDWAREINFO_DISK,"LICENSE_RET_ERROR_HARDWAREINFO_DISK")\
XX(0x21080, LICENSE_RET_ERROR_HARDWAREINFO_CPU,"LICENSE_RET_ERROR_HARDWAREINFO_CPU")\
XX(0x21090, LICENSE_RET_ERROR_DATE,"LICENSE_RET_ERROR_DATE")\
XX(0x210A0, LICENSE_RET_ERROR_VERIFY_FAILED,"LICENSE_RET_ERROR_VERIFY_FAILED")\
XX(0x30000,FOLLOW_RET_SUCCESS,"FOLLOW_RET_SUCCESS")\
XX(0x30101,FOLLOW_RET_SUCCESS_POSITION_PATCH,"FOLLOW_RET_SUCCESS_POSITION_PATCH")\
XX(0x30102,FOLLOW_RET_SUCCESS_REQUEST_ACCEPTED,"FOLLOW_RET_SUCCESS_REQUEST_ACCEPTED")\
XX(0x30103,FOLLOW_RET_SUCCESS_CREATE_CON,"FOLLOW_RET_SUCCESS_CREATE_CON")\
XX(0x30104,FOLLOW_RET_SUCCESS_DELETE_CON,"FOLLOW_RET_SUCCESS_DELETE_CON")\
XX(0x31000,FOLLOW_RET_ERROR,"FOLLOW_RET_ERROR")\
XX(0x31101,FOLLOW_RET_ERROR_LOGIN_PASSWORD,"FOLLOW_RET_ERROR_LOGIN_PASSWORD")\
XX(0x31102,FOLLOW_RET_ERROR_LOGIN_REPEAT,"FOLLOW_RET_ERROR_LOGIN_REPEAT")\
XX(0x31103,FOLLOW_RET_ERROR_LOGIN_UNSUPPORTED_SERVICEOBJ_TYPE,"FOLLOW_RET_ERROR_LOGIN_UNSUPPORTED_SERVICEOBJ_TYPE")\
XX(0x31104,FOLLOW_RET_ERROR_POSITION_PATCH,"FOLLOW_RET_ERROR_POSITION_PATCH")\
XX(0x31105,FOLLOW_RET_ERROR_REQUEST_ACCEPTED,"FOLLOW_RET_ERROR_REQUEST_ACCEPTED")\
XX(0x31106,FOLLOW_RET_ERROR_CREATE_CON,"FOLLOW_RET_ERROR_CREATE_CON")\
XX(0x31107,FOLLOW_RET_ERROR_DELETE_CON,"FOLLOW_RET_ERROR_DELETE_CON")\
XX(0x31108,FOLLOW_RET_ERROR_SIGNAL_TYPE,"FOLLOW_RET_ERROR_SIGNAL_TYPE")\
XX(0x31109,FOLLOW_RET_ERROR_FOLLOW_PATCH_OPEN_SIGNAL_NOTFOUND,"FOLLOW_RET_ERROR_FOLLOW_PATCH_OPEN_SIGNAL_NOTFOUND")\
XX(0x3110A,FOLLOW_RET_ERROR_FOLLOWCON_INVALID,"FOLLOW_RET_ERROR_FOLLOWCON_INVALID")\
XX(0x3110B,FOLLOW_RET_ERROR_FOLLOWCON_EMPTY,"FOLLOW_RET_ERROR_FOLLOWCON_EMPTY")\
XX(0x3110C,FOLLOW_RET_ERROR_SYSTEM_BUSY,"FOLLOW_RET_ERROR_SYSTEM_BUSY")\
XX(0x40000,GATEWAY_RET_SUCCESS,"GATEWAY_RET_SUCCESS")\
XX(0x41000,GATEWAY_RET_ERROR,"GATEWAY_RET_ERROR")\
XX(0x41100,GATEWAY_RET_ERROR_LOGIN,"GATEWAY_RET_ERROR")\
XX(0x41101,GATEWAY_RET_ERROR_LOGIN_PASSWORD,"GATEWAY_RET_ERROR_LOGIN_PASSWORD")\
XX(0x41200,GATEWAY_RET_ERROR_DATA,"GATEWAY_RET_ERROR_DATA")\
XX(0x41210,GATEWAY_RET_ERROR_DATA_EMPTY,"GATEWAY_RET_ERROR_DATA_EMPTY")\
XX(0x41220,GATEWAY_RET_ERROR_EXCHANGE_DISCONNECTED,"GATEWAY_RET_ERROR_EXCHANGE_DISCONNECTED")\
XX(0x41230,GATEWAY_RET_ERROR_PROCESS_ORDER_TIMEOUT,"GATEWAY_RET_ERROR_PROCESS_ORDER_TIMEOUT")\
XX(0x41240,GATEWAY_RET_ERROR_REQUEST_ORDER,"GATEWAY_RET_ERROR_REQUEST_ORDER")\
XX(0x41250,GATEWAY_RET_ERROR_PRODUCTCON_NOTFOUND,"GATEWAY_RET_ERROR_PRODUCTCON_NOTFOUND")\
XX(0x41260,GATEWAY_RET_ERROR_SYSTEMPRODUCTID_NULL,"GATEWAY_RET_ERROR_SYSTEMPRODUCTID_NULL")\
XX(0x41270,GATEWAY_RET_ERROR_ORDERTASK_DISABLE,"GATEWAY_RET_ERROR_ORDERTASK_DISABLE")\
XX(0x41280,GATEWAY_RET_ERROR_MTORDERID_INVALID,"GATEWAY_RET_ERROR_MTORDERID_INVALID")\
XX(0x41290,GATEWAY_RET_ERROR_ORDER_VOLUME_INVALID,"GATEWAY_RET_ERROR_ORDER_VOLUME_INVALID")\
XX(0x41310,GATEWAY_RET_ERROR_ORDER_ACTION_NONSUPPORT,"GATEWAY_RET_ERROR_ORDER_ACTION_NONSUPPORT")\
XX(0x41320,GATEWAY_RET_ERROR_ORDER_SYSTEMORDERID_INVALID,"GATEWAY_RET_ERROR_ORDER_SYSTEMORDERID_INVALID")\
XX(0x41330,GATEWAY_RET_ERROR_ORDER_REQUEST_TYPE,"GATEWAY_RET_ERROR_ORDER_REQUEST_TYPE")\
XX(0x41340,GATEWAY_RET_ERROR_ORDER_REQUEST_TIMEOUT,"GATEWAY_RET_ERROR_ORDER_REQUEST_TIMEOUT")\
XX(0x50000,PROXY_RET_SUCCESS,"PROXY_RET_SUCCESS")\
XX(0x50100,PROXY_RET_SUCCESS_ORDER_ACCEPTED,"PROXY_RET_SUCCESS_ORDER_ACCEPTED")\
XX(0x51000,PROXY_RET_ERROR,"PROXY_RET_ERROR")\
XX(0x51100,PROXY_RET_ERROR_LOGIN,"PROXY_RET_ERROR_LOGIN")\
XX(0x51101,PROXY_RET_ERROR_LOGIN_PASSWORD,"PROXY_RET_ERROR_LOGIN_PASSWORD")\
XX(0x51102,PROXY_RET_ERROR_LOGIN_REPEAT,"PROXY_RET_ERROR_LOGIN_REPEAT")\
XX(0x51103,PROXY_RET_ERROR_LOGIN_UNSUPPORTED_SERVICEOBJ_TYPE,"PROXY_RET_ERROR_LOGIN_UNSUPPORTED_SERVICEOBJ_TYPE")\
XX(0x51200,PROXY_RET_ERROR_PRODUCTCON,"PROXY_RET_ERROR_PRODUCTCON")\
XX(0x51201,PROXY_RET_ERROR_PRODUCTCON_NOTFOUND,"PROXY_RET_ERROR_PRODUCTCON_NOTFOUND")\
XX(0x51202,PROXY_RET_ERROR_PRODUCTCON_NOTFOUND_GATEWAY,"PROXY_RET_ERROR_PRODUCTCON_NOTFOUND_GATEWAY")\
XX(0x51203,PROXY_RET_ERROR_PRODUCTCON_NOTFOUND_EXCHANGE,"PROXY_RET_ERROR_PRODUCTCON_NOTFOUND_EXCHANGE")\
XX(0x51204,PROXY_RET_ERROR_PRODUCTCON_NOTFOUND_SYSTEM,"PROXY_RET_ERROR_PRODUCTCON_NOTFOUND_SYSTEM")\
XX(0x51300,PROXY_RET_ERROR_INVALID,"PROXY_RET_ERROR_INVALID")\
XX(0x51301,PROXY_RET_ERROR_INVALID_ID,"PROXY_RET_ERROR_INVALID_ID")\
XX(0x51302,PROXY_RET_ERROR_INVALID_SYSTEM_PRODUCT_ID,"PROXY_RET_ERROR_INVALID_SYSTEM_PRODUCT_ID")\
XX(0x51303,PROXY_RET_ERROR_INVALID_ORDER_SIDE,"PROXY_RET_ERROR_INVALID_ORDER_SIDE")\
XX(0x51304,PROXY_RET_ERROR_INVALID_GATEWAY_PRODUCT_ID,"PROXY_RET_ERROR_INVALID_GATEWAY_PRODUCT_ID")\
XX(0x51305,PROXY_RET_ERROR_INVALID_ORDER_VOLUME,"PROXY_RET_ERROR_INVALID_ORDER_VOLUME")\
XX(0x51306,PROXY_RET_ERROR_INVALID_ORDER_PRICE,"PROXY_RET_ERROR_INVALID_ORDER_PRICE")\
XX(0x51307,PROXY_RET_ERROR_INVALID_CLIENT_ID,"PROXY_RET_ERROR_INVALID_CLIENT_ID")\
XX(0x51400,PROXY_RET_ERROR_EXCHANGE,"PROXY_RET_ERROR_EXCHANGE")\
XX(0x51401,PROXY_RET_ERROR_EXCHANGE_NOTFOUND,"PROXY_RET_ERROR_EXCHANGE_NOTFOUND")\
XX(0x51500,PROXY_RET_ERROR_VOLUME,"PROXY_RET_ERROR_VOLUME")\
XX(0x51501,PROXY_RET_ERROR_VOLUME_MINLIMIT,"PROXY_RET_ERROR_VOLUME_MINLIMIT")\
XX(0x51502,PROXY_RET_ERROR_VOLUME_MAXLIMIT,"PROXY_RET_ERROR_VOLUME_MAXLIMIT")\
XX(0x51503,PROXY_RET_ERROR_ORDER_MINVOLUME_INVALID,"PROXY_RET_ERROR_ORDER_MINVOLUME_INVALID")\
XX(0x51600,PROXY_RET_ERROR_ORDER,"PROXY_RET_ERROR_ORDER")\
XX(0x50600,PROXY_RET_SUCCESS_ORDER,"PROXY_RET_SUCCESS_ORDER")\
XX(0x51601,PROXY_RET_ERROR_ORDER_REQUEST,"PROXY_RET_ERROR_ORDER_REQUEST")\
XX(0x51602,PROXY_RET_ERROR_ORDER_REQUEST_ACK,"PROXY_RET_ERROR_ORDER_REQUEST_ACK")\
XX(0x51603,PROXY_RET_ERROR_ORDER_REQUEST_RES,"PROXY_RET_ERROR_ORDER_REQUEST_RES")\
XX(0x51604,PROXY_RET_ERROR_ORDER_TIMEOUT, "PROXY_RET_ERROR_ORDER_TIMEOUT")\
XX(0x51605,PROXY_RET_ERROR_ORDER_TASK, "PROXY_RET_ERROR_ORDER_TASK")\
XX(0x51606, PROXY_RET_ERROR_ORDER_TASK_BUSY, "PROXY_RET_ERROR_ORDER_TASK_BUSY")\
XX(0x51607, PROXY_RET_ERROR_ORDER_ID, "PROXY_RET_ERROR_ORDER_ID")\
XX(0x51700,PROXY_RET_ERROR_PROCESS, "PROXY_RET_ERROR_PROCESS")\
XX(0x51701,PROXY_RET_ERROR_PROCESS_NOT_EXECUTED, "PROXY_RET_ERROR_PROCESS_NOT_EXECUTED")\
XX(0x51702,PROXY_RET_ERROR_PROCESS_READY, "PROXY_RET_ERROR_PROCESS_READY")\
XX(0x60000,EXCHANGE_RET_SUCCESS,"EXCHANGE_RET_SUCCESS")\
XX(0x60100,EXCHANGE_RET_SUCCESS_ORDER_ACCEPTED,"EXCHANGE_RET_SUCCESS_ORDER_ACCEPTED")\
XX(0x60200,EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_ACCEPTED,"EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_ACCEPTED")\
XX(0x60300,EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_REPLACED,"EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_REPLACED")\
XX(0x60400,EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_CANCELLED,"EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_CANCELLED")\
XX(0x60500,EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_TRADE,"EXCHANGE_RET_SUCCESS_ORDER_EXECTYPE_TRADE")\
XX(0x60510,EXCHANGE_RET_SUCCESS_ORDER_STATUS_FILLED,"EXCHANGE_RET_SUCCESS_ORDER_STATUS_FILLED")\
XX(0x60520,EXCHANGE_RET_SUCCESS_ORDER_STATUS_PARTIALLYFILLED,"EXCHANGE_RET_SUCCESS_ORDER_STATUS_PARTIALLYFILLED")\
XX(0x61000,EXCHANGE_RET_ERROR,"EXCHANGE_RET_ERROR")\
XX(0x61100,EXCHANGE_RET_ERROR_NETWORK,"EXCHANGE_RET_ERROR_NETWORK")\
XX(0x61110,EXCHANGE_RET_ERROR_NETWORK_DISCONNECT,"EXCHANGE_RET_ERROR_NETWORK_DISCONNECT")\
XX(0x61200,EXCHANGE_RET_ERROR_DATA,"EXCHANGE_RET_ERROR_DATA")\
XX(0x61210,EXCHANGE_RET_ERROR_DATA_EMPTY,"EXCHANGE_RET_ERROR_DATA_EMPTY")\
XX(0x61211,EXCHANGE_RET_ERROR_DATA_REJECTED,"EXCHANGE_RET_ERROR_DATA_REJECTED")\
XX(0x61010,EXCHANGE_RET_ERROR_PRODUCT_NOTFOUND,"EXCHANGE_RET_ERROR_PRODUCT_NOTFOUND")\
XX(0x61020,EXCHANGE_RET_ERROR_REQUEST,"EXCHANGE_RET_ERROR_REQUEST")\
XX(0x61021,EXCHANGE_RET_ERROR_REQUEST_PROCESS_BUSY,"EXCHANGE_RET_ERROR_REQUEST_PROCESS_BUSY")\
XX(0x61030,EXCHANGE_RET_ERROR_REQUEST_QUEUE_FULL,"EXCHANGE_RET_ERROR_REQUEST_QUEUE_FULL")\
XX(0x61040,EXCHANGE_RET_ERROR_ORDER,"EXCHANGE_RET_ERROR_ORDER")\
XX(0x61041,EXCHANGE_RET_ERROR_ORDER_EXECTYPE_REJECTED,"EXCHANGE_RET_ERROR_ORDER_EXECTYPE_REJECTED")\
XX(0x61042,EXCHANGE_RET_ERROR_ORDER_TIMEOUT,"EXCHANGE_RET_ERROR_ORDER_TIMEOUT")\
XX(0x61043,EXCHANGE_RET_ERROR_ORDER_REJECTED_LACK_OF_MARKET_LIQUIDITY,"EXCHANGE_RET_ERROR_ORDER_REJECTED_LACK_OF_MARKET_LIQUIDITY")\
XX(0x61044,EXCHANGE_RET_ERROR_LMAX_ILLEGAL_STOP_PRICE_FOR_STOP_ORDER,"LMAX_Illegal stop price for stop order")\
XX(0x61045,EXCHANGE_RET_ERROR_LMAX_ILLEGAL_PRICE_FOR_STOP_ORDER,"LMAX_Illegal price for stop order")\
XX(0x61046, EXCHANGE_RET_ERROR_LMAX_TEMPORARY_SUSPENSION, "LMAX_TEMPORARY_SUSPENSION")\
XX(0x61047,EXCHANGE_RET_ERROR_LMAX_MAXIMUM_POSITION_EXCEEDED,"LMAX_MAXIMUM_POSITION_EXCEEDED")\
XX(0x61048, EXCHANGE_RET_ERROR_LMAX_INSTRUMENT_NOT_OPEN, "LMAX_INSTRUMENT_NOT_OPEN")\
XX(0x61049,EXCHANGE_RET_ERROR_LMAX_ILLEGAL_PRICE_FOR_MARKET_ORDER,"LMAX_Illegal price for market order")\
XX(0x61050, EXCHANGE_RET_ERROR_ORDER_REJECTED, "EXCHANGE_RET_ERROR_ORDER_REJECTED")\
XX(0x61051,EXCHANGE_RET_ERROR_ORDER_TRADE_RECORD_REQUEST,"EXCHANGE_RET_ERROR_ORDER_TRADE_RECORD_REQUEST")\
XX(0x61052,EXCHANGE_RET_ERROR_ORDER_STATUS_REQUEST,"EXCHANGE_RET_ERROR_ORDER_STATUS_REQUEST")\
XX(0x62010,EXHANGE_RET_ERROR_ORDER_CFH_QUANTITY_NOT_AVAILABLE_FOR_FOK_ORDER,"CFH_Quantity not available for FoK order")\
XX(0x62011,EXHANGE_RET_ERROR_ORDER_CFH_REJECTED,"CFH_MarginExceeded: Margin would be exceeded")\


//Rejected
#define SK_ERRNO_GEN(code, type, desc) type = code,
	enum struct SKAPIRES : __int64
	{
		SK_ERRNO_MAP(SK_ERRNO_GEN)
		SK_MAX_ERRORS
	};
#undef SK_ERRNO_GEN

	inline bool SKAPIRES_SUCCESS(const SKAPIRES& code)
	{
		return !(__int64(code) & 0xF000);
	}

	inline bool SKAPIRES_SUCCESS(const __int64& code)
	{
		return !(code & 0xF000);
	}

	inline bool SKAPIRES_FAILED(const SKAPIRES& code)
	{
		return __int64(code) & 0xF000;
	}

	inline bool SKAPIRES_FAILED(const __int64& code)
	{
		return code & 0xF000;
	}

#define SK_STRERROR_GEN(code, type, desc) case SKAPIRES::type : return desc;
	inline const char* SKAPIRES_DESC(const SKAPIRES& code) {
		switch (SKAPIRES(code)) {
			SK_ERRNO_MAP(SK_STRERROR_GEN)
		default:
			return "unknown error";
		}
	}
#undef SK_STRERROR_GEN

#define SK_ERR_NAME_GEN(code, type, desc) case SKAPIRES::type : return #type;
	inline const char* SKAPIRES_NAME(const SKAPIRES& code) {
		switch (code) {
			SK_ERRNO_MAP(SK_ERR_NAME_GEN)
		default:
			return "unknown name";
		}
	}
#undef SK_ERR_NAME_GEN




/// /*新生联创（上海）**/
/// /*2019年08月14日 13:47:10|991**/
/// /*_ _ _ _ _ _ _ www.skstu.com _ _ _ _ _ _ _**/
#endif ///AFX_SKSTU_ERROR_H__5147C_79417AF0_5FFEDD3EDE4B655_7F16__TAIL__